version: '3.7'
services: 
    db:
        image: mysql
        container_name: db_docker_exemple
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_exemple
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev
    www:
        build: php
        container_name: www_docker_symfony
        ports:
            - "8741:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        user: '1000:1000' 
        restart: always
        networks:
            - dev
        
networks:
    dev:
volumes:
    db-data: